import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowLeft,ArrowRight,AudioLines,Check,ChevronDown,ChevronRight,Clock3,Disc3,FileAudio,FolderOpen,Heart,ImagePlus,Library,Loader2,MoreHorizontal,Music2,PenLine,Play,Plus,Search,Settings2,SlidersHorizontal,Sparkles,Trash2,Upload,X} from 'lucide-react';
import {api,fileData,setToken} from './api';
import {Cover,duration,Empty,Mark,Modal,Player,Status,timeAgo} from './components';
import SettingsDialog from './SettingsDialog';
import {draftFields,emptyTrack,type Engine,type Settings,type Take,type Track} from './types';

type View='compose'|'library'|'queue';
const genres=['Indie folk','Electronic','Jazz','Ambient','Alternative','Soul'];
const prompts:Record<string,string>={
 'Indie folk':'English, intimate indie folk, warm close vocal, fingerpicked acoustic guitar, brushed drums, natural room sound',
 'Electronic':'English, atmospheric electronic, understated vocal, analog synthesizers, deep bass, detailed percussion',
 'Jazz':'English, late-night jazz, expressive warm vocal, upright bass, brushed drums, muted trumpet, piano',
 'Ambient':'English, ambient art pop, breathy vocal, slowly evolving textures, soft piano, spacious reverb',
 'Alternative':'English, alternative rock, textured guitar, live drums, expressive vocal, dynamic chorus',
 'Soul':'English, warm soul, rich vocal, Rhodes piano, round bass, restrained drums, intimate production'
};
const starterLyrics='[Verse]\nThe last light settles on the floor\nA quiet street, an open door\nI leave the noise a mile behind\nAnd take the long way home tonight\n\n[Chorus]\nLet the evening move us slowly\nLet the little things remain\nThere is something in the silence\nI would like to hear again';
const active=(take:Take)=>['queued','running'].includes(take.status);

export default function App(){
 const [loaded,setLoaded]=useState(false);const [fatal,setFatal]=useState('');const [tracks,setTracks]=useState<Track[]>([]);const [draft,setDraft]=useState<Track>(emptyTrack);const draftRef=useRef(draft);draftRef.current=draft;
 const [view,setView]=useState<View>('compose');const [tab,setTab]=useState<'lyrics'|'score'>('lyrics');const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');const [engine,setEngine]=useState<Engine>({ready:false,status:'checking',message:'Checking your music engine…',device:'auto',python_path:'',model_cached:false,runtime_available:false});
 const [settings,setSettings]=useState<Settings>({python_path:'',device:'auto',memory_budget_gib:12,model:'m-a-p/YuE2-3B',vae:'m-a-p/YuE2-Vae',offline:true,mode:'local',remote_url:'http://127.0.0.1:8767'});
 const [settingsOpen,setSettingsOpen]=useState(false);const [artOpen,setArtOpen]=useState(false);const [deleteTrack,setDeleteTrack]=useState<Track|null>(null);const [artKey,setArtKey]=useState('');const [artPrompt,setArtPrompt]=useState('');const [busy,setBusy]=useState('');const [dirty,setDirty]=useState(false);const [saveState,setSaveState]=useState('');const [notice,setNotice]=useState<{text:string,error?:boolean}|null>(null);
 const [playingTrack,setPlayingTrack]=useState<Track|null>(null);const [playingTakeId,setPlayingTakeId]=useState('');const audioInput=useRef<HTMLInputElement>(null);const coverInput=useRef<HTMLInputElement>(null);const scoreInput=useRef<HTMLInputElement>(null);const lyricInput=useRef<HTMLTextAreaElement>(null);
 const saveChain=useRef<Promise<Track>|null>(null);const dirtyRef=useRef(false);dirtyRef.current=dirty;const noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const toast=useCallback((text:string,error=false)=>{setNotice({text,error});if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(null),error?9000:4000);},[]);
 const acceptTrack=useCallback((track:Track)=>{setTracks(list=>{const exists=list.some(t=>t.id===track.id);return (exists?list.map(t=>t.id===track.id?track:t):[track,...list]).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));});setPlayingTrack(p=>p?.id===track.id?track:p);},[]);
 const save=useCallback(async():Promise<Track>=>{
   if(saveChain.current){await saveChain.current;}
   const snapshot=draftRef.current;setSaveState('Saving…');
   const promise=api<{track:Track}>(snapshot.id?`/api/tracks/${snapshot.id}`:'/api/tracks',snapshot.id?'PATCH':'POST',draftFields(snapshot)).then(({track})=>{acceptTrack(track);if(JSON.stringify(draftFields(draftRef.current))===JSON.stringify(draftFields(snapshot))){draftRef.current=track;setDraft(track);setDirty(false);}else if(!draftRef.current.id&&!snapshot.id){draftRef.current={...draftRef.current,id:track.id};setDraft(draftRef.current);}setSaveState('Saved locally');return track;}).catch(e=>{setSaveState('Not saved');throw e;}).finally(()=>{if(saveChain.current===promise)saveChain.current=null;});
   saveChain.current=promise;return promise;
 },[acceptTrack]);
 useEffect(()=>{let cancelled=false;api<{csrf:string;tracks:Track[];settings:Settings;engine:Engine}>('/api/bootstrap').then(data=>{if(cancelled)return;setToken(data.csrf);setTracks(data.tracks);setSettings(data.settings);setEngine(data.engine);setLoaded(true);}).catch(e=>{if(!cancelled)setFatal(e.message);});return()=>{cancelled=true;};},[]);
 useEffect(()=>{if(!dirty||!loaded)return;const timer=setTimeout(()=>{save().catch(e=>toast(e.message,true));},1000);return()=>clearTimeout(timer);},[dirty,draft,loaded,save,toast]);
 useEffect(()=>{if(!loaded)return;let gone=false;const timer=setInterval(()=>{api<{tracks:Track[]}>('/api/tracks').then(({tracks:next})=>{if(gone)return;setTracks(next);const latest=next.find(t=>t.id===draftRef.current.id);if(latest){setDraft(previous=>({...previous,takes:latest.takes,cover_url:latest.cover_url,cover_status:latest.cover_status,cover_error:latest.cover_error}));}setPlayingTrack(previous=>previous?next.find(t=>t.id===previous.id)||previous:previous);}).catch(()=>{});},2500);return()=>{gone=true;clearInterval(timer);};},[loaded]);
 const update=(value:Partial<Track>)=>{setDraft(previous=>({...previous,...value}));setDirty(true);setSaveState('Unsaved changes');};
 const newSong=useCallback(async()=>{try{if(dirtyRef.current)await save();setDraft(emptyTrack());setDirty(false);setSaveState('');setView('compose');setTab('lyrics');}catch(e){toast((e as Error).message,true);}},[save,toast]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();save().then(()=>toast('Composition saved.')).catch(e=>toast(e.message,true));}if((e.metaKey||e.ctrlKey)&&e.key==='n'){e.preventDefault();void newSong();}};window.addEventListener('keydown',handler);const before=(e:BeforeUnloadEvent)=>{if(dirtyRef.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>{window.removeEventListener('keydown',handler);window.removeEventListener('beforeunload',before);};},[save,newSong,toast]);
 async function openTrack(track:Track){try{if(dirtyRef.current)await save();setDraft(track);setDirty(false);setSaveState('Saved locally');setView('compose');setTab('lyrics');}catch(e){toast((e as Error).message,true);}}
 async function navigate(next:View){try{if(dirtyRef.current)await save();setView(next);}catch(e){toast((e as Error).message,true);}}
 async function generate(){if(!engine.ready){setSettingsOpen(true);return;}if(!draft.style.trim()){toast('Describe the sound or choose a style before generating.',true);return;}if(!draft.lyrics.trim()){toast('Add lyrics before generating.',true);return;}setBusy('generate');try{const current=await save();const {track}=await api<{track:Track}>(`/api/tracks/${current.id}/generate`,'POST',{});acceptTrack(track);setDraft(track);toast('A new take has been queued.');}catch(e){toast((e as Error).message,true);}finally{setBusy('');}}
 async function cancel(track:Track,take:Take){try{const result=await api<{track:Track}>(`/api/tracks/${track.id}/takes/${take.id}/cancel`,'POST',{});acceptTrack(result.track);if(track.id===draft.id)setDraft(previous=>({...previous,takes:result.track.takes}));toast('Take cancelled.');}catch(e){toast((e as Error).message,true);}}
 async function upload(file:File,kind:'audio'|'cover'){const limit=kind==='audio'?80:12;if(file.size>limit*1024*1024){toast(`Choose a ${kind} file smaller than ${limit} MB.`,true);return;}setBusy(kind);try{const current=await save();const result=await api<{track:Track}>(`/api/tracks/${current.id}/${kind}`,'POST',{filename:file.name,data:await fileData(file)});acceptTrack(result.track);setDraft(result.track);if(kind==='audio'){const take=result.track.takes.at(-1);if(take){setPlayingTrack(result.track);setPlayingTakeId(take.id);}}toast(kind==='audio'?'Recording imported.':'Cover artwork saved.');}catch(e){toast((e as Error).message,true);}finally{setBusy('');}}
 function selectTake(track:Track,take:Take){if(!take.audio_url)return;setPlayingTrack(track);setPlayingTakeId(take.id);}
 async function chooseTake(take:Take){try{const current=await save();const result=await api<{track:Track}>(`/api/tracks/${current.id}`,'PATCH',{selected_take_id:take.id});acceptTrack(result.track);setDraft(result.track);selectTake(result.track,take);}catch(e){toast((e as Error).message,true);}}
 async function favorite(track:Track){try{const result=await api<{track:Track}>(`/api/tracks/${track.id}`,'PATCH',{favorite:!track.favorite});acceptTrack(result.track);if(draft.id===track.id)setDraft(previous=>({...previous,favorite:result.track.favorite}));}catch(e){toast((e as Error).message,true);}}
 async function remove(){if(!deleteTrack)return;setBusy('delete');try{await api(`/api/tracks/${deleteTrack.id}`,'DELETE');setTracks(previous=>previous.filter(t=>t.id!==deleteTrack.id));if(draft.id===deleteTrack.id){setDraft(emptyTrack());setDirty(false);}if(playingTrack?.id===deleteTrack.id){setPlayingTrack(null);setPlayingTakeId('');}setDeleteTrack(null);toast('Composition deleted.');}catch(e){toast((e as Error).message,true);}finally{setBusy('');}}
 function openArt(){setArtPrompt(draft.cover_prompt||'');setArtOpen(true);}
 async function generateArt(){if(!artPrompt.trim()||!artKey.trim()){toast('Add an artwork direction and a BFL API key.',true);return;}setBusy('artwork');try{const current=await save();const result=await api<{track:Track}>(`/api/tracks/${current.id}/artwork`,'POST',{prompt:artPrompt,api_key:artKey});acceptTrack(result.track);setDraft(result.track);setArtOpen(false);toast('Cover generation started. Your music stays unchanged.');}catch(e){toast((e as Error).message,true);}finally{setBusy('');}}
 function insertSection(section:string){const text=lyricInput.current;const current=draft.lyrics;const start=text?.selectionStart??current.length;const end=text?.selectionEnd??start;const insertion=`${start&&!current.slice(0,start).endsWith('\n\n')?'\n\n':''}[${section}]\n`;update({lyrics:current.slice(0,start)+insertion+current.slice(end)});requestAnimationFrame(()=>{text?.focus();text?.setSelectionRange(start+insertion.length,start+insertion.length);});}
 const selectedTake=draft.takes.find(t=>t.id===draft.selected_take_id)||[...draft.takes].reverse().find(t=>t.audio_url);
 const playingTake=playingTrack?.takes.find(t=>t.id===playingTakeId);
 const jobs=tracks.flatMap(track=>track.takes.map(take=>({track,take}))).sort((a,b)=>b.take.created_at.localeCompare(a.take.created_at));const liveJobs=jobs.filter(({take})=>active(take));
 const filtered=tracks.filter(t=>`${t.title} ${t.artist} ${t.album} ${t.style}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='favorites'&&t.favorite||filter==='ready'&&t.takes.some(take=>take.audio_url)||filter==='drafts'&&!t.takes.some(take=>take.audio_url)));
 if(fatal)return <div className="startup"><Mark/><h1>Studio could not connect</h1><p>{fatal}</p><button className="primary-button" onClick={()=>location.reload()}>Try again</button></div>;
 if(!loaded)return <div className="startup"><Mark/><Loader2 className="spin"/><p>Opening your studio…</p></div>;
 return <div className="app-shell">
 <aside className="sidebar"><div className="brand"><Mark/><div><strong>YuE<span>Studio</span></strong><small>MUSIC WORKSPACE</small></div></div><button className="new-song" onClick={()=>void newSong()}><Plus size={17}/>New composition<kbd>⌘ N</kbd></button><div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation"><button className={view==='compose'?'active':''} onClick={()=>void navigate('compose')}><PenLine size={18}/>Compose</button><button className={view==='library'?'active':''} onClick={()=>void navigate('library')}><Library size={18}/>Library<span>{tracks.length||''}</span></button><button className={view==='queue'?'active':''} onClick={()=>void navigate('queue')}><AudioLines size={18}/>Generation queue{liveJobs.length>0&&<span className="count">{liveJobs.length}</span>}</button></nav><div className="sidebar-recent"><div className="nav-label">RECENT COMPOSITIONS</div>{tracks.slice(0,5).map(track=><button key={track.id} className={draft.id===track.id?'current':''} onClick={()=>void openTrack(track)}><span className="recent-dot"/><span>{track.title||'Untitled composition'}</span></button>)}{tracks.length===0&&<p>Your compositions will<br/>appear here.</p>}</div><div className="sidebar-bottom"><button className="engine-card" onClick={()=>setSettingsOpen(true)}><span className={`engine-dot ${engine.ready?'ready':''}`}/><div><strong>{engine.ready?'Music engine ready':'Connect your engine'}</strong><small>{engine.ready?engine.device||'Local runtime':'Set up local or remote generation'}</small></div><ChevronRight size={15}/></button><div className="sidebar-foot"><span>LOCAL WORKSPACE</span><button className="icon-button" aria-label="Open settings" onClick={()=>setSettingsOpen(true)}><Settings2 size={17}/></button></div></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><ChevronRight size={13}/><strong>{view==='compose'?'Compose':view==='library'?'Library':'Generation queue'}</strong></div><div className="top-actions"><span className="local-indicator"><i/>Stored on your Mac</span><button className="icon-button" aria-label="Engine settings" onClick={()=>setSettingsOpen(true)}><SlidersHorizontal size={17}/></button></div></header>
 <main className={`main-content ${view}`}>
 {view==='compose'?<><div className="page-heading"><div><div className="eyebrow">THE COMPOSITION DESK</div><h1>{draft.id?'Your composition':'A new composition'}</h1><p>Give your words a sound of their own.</p></div><div className="heading-actions"><span className="save-state" aria-live="polite">{saveState==='Saved locally'?<Check size={13}/>:saveState==='Saving…'?<Loader2 size={13} className="spin"/>:null}{saveState}</span><button className="secondary-button" onClick={()=>audioInput.current?.click()} disabled={!!busy}><Upload size={15}/>{busy==='audio'?'Importing…':'Import audio'}</button><button className="primary-button top-generate" onClick={()=>void generate()} disabled={!!busy}>{busy==='generate'?<Loader2 size={15} className="spin"/>:<AudioLines size={15}/>}Generate take<ArrowRight size={14}/></button>{draft.id&&<button className="icon-button more-button" aria-label="Delete this composition" onClick={()=>setDeleteTrack(draft)}><Trash2 size={16}/></button>}</div></div>
 <div className="composition-layout"><section className="composition-sheet"><div className="identity-fields"><input className="song-title" aria-label="Song title" placeholder="Untitled composition" value={draft.title} maxLength={160} onChange={e=>update({title:e.target.value})}/><div className="credit-fields"><input aria-label="Artist name" placeholder="Artist name" value={draft.artist} maxLength={160} onChange={e=>update({artist:e.target.value})}/><span>/</span><input aria-label="Album name" placeholder="Album or collection" value={draft.album} maxLength={160} onChange={e=>update({album:e.target.value})}/></div></div>
 <div className="editor-tabs" role="tablist" aria-label="Composition input"><button role="tab" aria-selected={tab==='lyrics'} className={tab==='lyrics'?'active':''} onClick={()=>setTab('lyrics')}><PenLine size={14}/>Lyrics</button><button role="tab" aria-selected={tab==='score'} className={tab==='score'?'active':''} onClick={()=>setTab('score')}><Music2 size={15}/>Score<span>OPTIONAL</span></button><span className="editor-count">{tab==='lyrics'?`${draft.lyrics.trim()?draft.lyrics.trim().split(/\s+/).length:0} words`:draft.abc?'Custom score':'No score attached'}</span></div>
 {tab==='lyrics'?<><div className="section-tools"><span>ADD SECTION</span>{['Verse','Chorus','Bridge','Outro'].map(section=><button key={section} onClick={()=>insertSection(section)}><Plus size={11}/>{section}</button>)}</div><textarea ref={lyricInput} className="lyrics-editor" aria-label="Song lyrics" value={draft.lyrics} onChange={e=>update({lyrics:e.target.value})} placeholder={'[Verse]\nBegin with a line you want to hear.\n\n\n[Chorus]\nGive it something to come back to.'} spellCheck/><div className="editor-bottom"><span>Section labels help shape the song.</span><button className="text-button" onClick={()=>{if(draft.lyrics.trim()){toast('Start a new composition to use the example without replacing your lyrics.');return;}update({lyrics:starterLyrics});}}>Use example lyrics <ArrowRight size={13}/></button></div></>:<><div className="score-intro"><p>Add an ABC melody or chord score to guide the recording.</p><button className="secondary-button small" onClick={()=>scoreInput.current?.click()}><Upload size={13}/>Import .abc</button></div><textarea className="lyrics-editor score-editor" aria-label="ABC score" value={draft.abc} onChange={e=>update({abc:e.target.value,cot:draft.cot==='off'?'full':draft.cot})} placeholder={'X:1\nT:Your composition\nM:4/4\nL:1/8\nQ:1/4=90\nK:C\n\nPaste an ABC score here.'} spellCheck={false}/><div className="editor-bottom"><span>Score changes create a new complete recording.</span></div></>}
 <div className="sound-direction"><div className="section-title"><span><SlidersHorizontal size={15}/>Sound direction</span><small>STYLE, INSTRUMENTS & VOICE</small></div><div className="genre-pills">{genres.map(genre=><button key={genre} className={draft.style===prompts[genre]?'selected':''} onClick={()=>update({style:prompts[genre]})}>{genre}</button>)}</div><textarea aria-label="Sound direction" value={draft.style} onChange={e=>update({style:e.target.value})} placeholder="Describe the genre, instruments, language, and vocal character…" rows={3}/></div>
 <details className="advanced"><summary><Settings2 size={14}/>Generation settings<ChevronDown size={14}/></summary><div className="advanced-fields"><label>Composition planning<select value={draft.cot} onChange={e=>update({cot:e.target.value as Track['cot'],...(e.target.value==='off'?{abc:''}:{})})}><option value="full">Melody & chords</option><option value="melody">Melody only</option><option value="off">Direct generation</option></select></label><label>Seed <small>Blank for a new variation</small><input type="number" min="0" max="2147483647" value={draft.seed??''} onChange={e=>update({seed:e.target.value===''?null:+e.target.value})} placeholder="Random"/></label></div></details>
 <div className="generate-bar"><div><span className={`engine-dot ${engine.ready?'ready':''}`}/><span>{engine.ready?'Ready to record a new take':'Music engine needs setup'}</span></div><button className="primary-button generate-button" onClick={()=>void generate()} disabled={!!busy}>{busy==='generate'?<Loader2 className="spin" size={17}/>:<AudioLines size={17}/>}Generate take<ArrowRight size={15}/></button></div></section>
 <aside className="right-column"><section className="artwork-panel"><div className="section-title"><span>Cover artwork</span><button className="icon-button" aria-label="Upload cover artwork" onClick={()=>coverInput.current?.click()}><ImagePlus size={16}/></button></div><Cover track={draft} large/>{['queued','running','generating'].includes(draft.cover_status||'')?<div className="artwork-working"><Loader2 size={14} className="spin"/>Creating your cover…</div>:<div className="cover-caption"><span>{draft.cover_url?'YOUR SELECTED COVER':'A SLEEVE FOR YOUR SOUND'}</span><p>{draft.cover_url?'Change the artwork whenever you like.':'Generate a cover from your visual direction, or bring your own.'}</p></div>}<div className="artwork-actions"><button className="secondary-button" onClick={openArt} disabled={['queued','running','generating'].includes(draft.cover_status||'')}><Sparkles size={14}/>{draft.cover_url?'Create another':'Create cover'}</button><button className="icon-button outlined" onClick={()=>coverInput.current?.click()} aria-label="Upload cover image" disabled={busy==='cover'}>{busy==='cover'?<Loader2 size={16} className="spin"/>:<Upload size={16}/>}</button></div>{draft.cover_error&&<p className="inline-error">{draft.cover_error}</p>}</section>
 <section className="takes-panel"><div className="section-title"><span>Takes</span><span className="subtle-count">{draft.takes.length.toString().padStart(2,'0')}</span></div>{draft.takes.length===0?<div className="takes-empty"><AudioLines size={26} strokeWidth={1.2}/><p>Your first take starts here.</p><span>Every generation is saved separately,<br/>so you can compare and keep exploring.</span></div>:<div className="take-list">{[...draft.takes].reverse().map((take,index)=><div className={`take-item ${selectedTake?.id===take.id?'selected':''}`} key={take.id}><div className="take-top"><button className="take-play" aria-label={`Play take ${draft.takes.length-index}`} disabled={!take.audio_url} onClick={()=>selectTake(draft,take)}>{active(take)?<Loader2 size={14} className="spin"/>:<Play size={13} fill="currentColor"/>}</button><div><strong>Take {String(draft.takes.length-index).padStart(2,'0')}</strong><span>{take.duration?duration(take.duration):timeAgo(take.created_at)}</span></div>{take.audio_url?<button className={`icon-button take-select ${selectedTake?.id===take.id?'selected':''}`} aria-label={`Select take ${draft.takes.length-index}`} title="Use this take for export" onClick={()=>void chooseTake(take)}><Check size={14}/></button>:active(take)?<button className="icon-button" aria-label="Cancel generation" onClick={()=>void cancel(draft,take)}><X size={14}/></button>:null}</div><Status take={take}/>{take.error&&<p className="inline-error">{take.error}</p>}</div>)}</div>}{selectedTake?.audio_url&&<a className="export-link" href={`/api/tracks/${draft.id}/export?take=${selectedTake.id}`} download><ArrowDownToLine size={14}/>Export selected take & artwork<ArrowRight size={13}/></a>}</section><p className="desk-note"><FolderOpen size={13}/> Originals and alternate takes stay in your library.</p></aside></div></>:
 view==='library'?<><div className="page-heading"><div><div className="eyebrow">YOUR RECORDINGS & IDEAS</div><h1>Library<span className="heading-count">{tracks.length}</span></h1><p>Every composition, from the first line to the final take.</p></div><button className="primary-button" onClick={()=>void newSong()}><Plus size={16}/>New composition</button></div><div className="library-toolbar"><div className="filter-tabs">{[['all','All compositions'],['ready','With audio'],['drafts','Drafts'],['favorites','Favorites']].map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div><label className="search-input"><Search size={16}/><input aria-label="Search library" placeholder="Find a composition…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button className="icon-button" aria-label="Clear search" onClick={()=>setSearch('')}><X size={13}/></button>}</label></div>{filtered.length?<div className="library-grid">{filtered.map(track=>{const take=track.takes.find(t=>t.id===track.selected_take_id)||[...track.takes].reverse().find(t=>t.audio_url);return <article className="track-card" key={track.id}><button className="card-cover" aria-label={`Open ${track.title||'Untitled composition'}`} onClick={()=>void openTrack(track)}><Cover track={track}/></button><div className="card-content"><div className="card-title"><button onClick={()=>void openTrack(track)}>{track.title||'Untitled composition'}</button><button className={`icon-button favorite ${track.favorite?'selected':''}`} aria-label={track.favorite?'Remove favorite':'Favorite composition'} onClick={()=>void favorite(track)}><Heart size={15} fill={track.favorite?'currentColor':'none'}/></button></div><p>{track.artist||track.album||'Independent composition'}</p><div className="card-foot"><span>{take?`${track.takes.length} ${track.takes.length===1?'take':'takes'} · ${duration(take.duration)}`:'Draft'}<i/> {timeAgo(track.updated_at)}</span>{take?<button className="icon-button" aria-label={`Play ${track.title||'composition'}`} onClick={()=>selectTake(track,take)}><Play size={14} fill="currentColor"/></button>:<PenLine size={13}/>}</div></div></article>;})}</div>:<Empty title={search?'No matching compositions':filter==='favorites'?'Your favorites will live here':'A library waiting for its first song'}>{search?'Try a title, artist, or musical style.':filter==='favorites'?'Use the heart on a composition to keep it close.':'Save a composition or import a recording to start your collection.'}</Empty>}</>:
 <><div className="page-heading"><div><div className="eyebrow">RECORDING ACTIVITY</div><h1>Generation queue</h1><p>{liveJobs.length?`${liveJobs.length} ${liveJobs.length===1?'take':'takes'} in progress. You can keep composing while you wait.`:'A record of your takes, including anything that needs another try.'}</p></div><span className="queue-capacity"><i/>One music job at a time</span></div>{jobs.length?<div className="queue-list">{jobs.map(({track,take})=><article className="queue-item" key={take.id}><div className="queue-art"><Cover track={track}/></div><div className="queue-info"><button onClick={()=>void openTrack(track)}>{track.title||'Untitled composition'}</button><span>{timeAgo(take.created_at)}{take.duration?` · ${duration(take.duration)}`:''}</span>{take.error&&<p className="inline-error">{take.error}</p>}</div><Status take={take}/>{active(take)?<button className="secondary-button small" onClick={()=>void cancel(track,take)}>Cancel</button>:take.audio_url?<button className="icon-button" aria-label="Play recording" onClick={()=>selectTake(track,take)}><Play size={16}/></button>:<button className="text-button" onClick={()=>void openTrack(track)}>Open composition<ArrowRight size={13}/></button>}</article>)}</div>:<Empty title="The studio is quiet">Generated and imported takes will appear here. Start a composition whenever you’re ready.</Empty>}</>}
 </main></div>
 <Player track={playingTrack} take={playingTake} onStep={delta=>{if(!playingTrack)return;const playable=playingTrack.takes.filter(t=>t.audio_url);const index=playable.findIndex(t=>t.id===playingTakeId);const take=playable[(index+delta+playable.length)%playable.length];if(take)setPlayingTakeId(take.id);}}/>
 <input ref={audioInput} type="file" accept="audio/wav,audio/x-wav,audio/flac,audio/mpeg,audio/mp4,.wav,.flac,.mp3,.m4a" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,'audio');e.target.value='';}}/><input ref={coverInput} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,'cover');e.target.value='';}}/><input ref={scoreInput} type="file" accept=".abc,.txt" hidden onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>512000)toast('Choose a score smaller than 500 KB.',true);else try{update({abc:await f.text(),cot:draft.cot==='off'?'full':draft.cot});}catch{toast('Could not read the score file.',true);}}e.target.value='';}}/>
 {settingsOpen&&<SettingsDialog settings={settings} engine={engine} onClose={()=>setSettingsOpen(false)} onSave={async value=>{const data=await api<{settings:Settings;engine:Engine}>('/api/settings','PATCH',value);setSettings(data.settings);setEngine(data.engine);toast(data.engine.ready?'Music engine connected.':'Connection settings saved.');}}/>}
 {artOpen&&<Modal title="Create cover artwork" subtitle="Give this recording a visual direction of its own." onClose={()=>setArtOpen(false)}><div className="art-dialog-body"><div className="provider-label"><Sparkles size={16}/><strong>FLUX.2 Pro</strong><span>1024 × 1024</span></div><label>Artwork direction<textarea value={artPrompt} onChange={e=>setArtPrompt(e.target.value)} maxLength={6000} rows={6} placeholder="An empty coastal observatory at dusk, weathered concrete, a single amber window. Medium-format photography, muted colors, no text."/><small>Only this description is sent. Your lyrics and audio stay here.</small></label><label>BFL API key<input type="password" autoComplete="off" value={artKey} onChange={e=>setArtKey(e.target.value)} placeholder="Your Black Forest Labs API key"/><small>Kept in memory for this session. Never saved with your project.</small></label><p className="provider-note">Generating submits one paid image request to your BFL account. Music generation is separate.</p></div><div className="modal-footer"><button className="text-button" onClick={()=>{setArtOpen(false);coverInput.current?.click();}}><Upload size={14}/>Upload an image instead</button><button className="primary-button" disabled={!!busy||!artPrompt.trim()||!artKey.trim()} onClick={()=>void generateArt()}>{busy==='artwork'?<Loader2 className="spin" size={15}/>:<Sparkles size={15}/>}Generate cover</button></div></Modal>}
 {deleteTrack&&<Modal title="Delete composition?" onClose={()=>setDeleteTrack(null)}><div className="delete-body"><p>“{deleteTrack.title||'Untitled composition'}” and its saved takes and artwork will be removed from this library.</p></div><div className="modal-footer"><button className="secondary-button" onClick={()=>setDeleteTrack(null)}>Keep composition</button><button className="danger-button" disabled={busy==='delete'} onClick={()=>void remove()}><Trash2 size={15}/>Delete composition</button></div></Modal>}
 {notice&&<div className={`toast ${notice.error?'error':''}`} role={notice.error?'alert':'status'}>{notice.error?<X size={16}/>:<Check size={16}/>}<span>{notice.text}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setNotice(null)}><X size={14}/></button></div>}
 </div>;
}
