import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowDownToLine,Check,Disc3,Loader2,Music2,Pause,Play,Repeat2,SkipBack,SkipForward,Volume2,X} from 'lucide-react';
import type {Track,Take} from './types';

export function Mark({small=false}:{small?:boolean}){return <svg className={small?'brand-mark small':'brand-mark'} width={small?50:66} height={small?20:27} viewBox="0 0 100 40" fill="none" aria-hidden="true"><ellipse cx="50" cy="20" rx="44" ry="14" stroke="currentColor" strokeWidth="1.44"/><circle cx="50" cy="20" r="1.9" fill="currentColor"/></svg>;}
export function Cover({track,large=false}:{track?:Partial<Track>;large?:boolean}){return <div className={`cover ${large?'cover-large':''} ${track?.cover_url?'has-image':''}`}>{track?.cover_url?<img src={track.cover_url} alt={`${track.title||'Untitled'} cover artwork`}/>:<><div className="sleeve-grain"/><div className="record-disc"><div className="record-label"><Mark small/></div></div><span className="sleeve-edition">AUDIO / FABRICATOR</span><span className="sleeve-note">{track?.title?'WORK IN PROGRESS':'YOUR NEXT RECORDING'}</span></>}</div>;}
export function Modal({title,subtitle,children,onClose,wide=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const root=useRef<HTMLDivElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement;root.current?.focus();const handler=(event:KeyboardEvent)=>{if(event.key==='Escape')close.current();if(event.key==='Tab'){const all=Array.from(root.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), textarea:not(:disabled), select:not(:disabled), a[href], [tabindex="0"]')||[]).filter(x=>x.offsetParent!==null);if(!all.length){event.preventDefault();return;}const first=all[0],last=all[all.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===root.current)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-labelledby="dialog-title" ref={root} tabIndex={-1}><div className="modal-head"><div><h2 id="dialog-title">{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</div></div>;
}
export function Status({take}:{take:Take}){const text=({queued:'Queued',running:take.stage||'Generating',complete:'Ready',needs_review:'Review ending',failed:'Failed',cancelled:'Cancelled'})[take.status];return <span className={`status ${take.status}`}>{take.status==='running'?<Loader2 size={12} className="spin"/>:take.status==='complete'?<Check size={12}/>:<i/>}{text}</span>;}
export function duration(value=0){if(!Number.isFinite(value))return '0:00';return `${Math.floor(value/60)}:${Math.floor(value%60).toString().padStart(2,'0')}`;}
export function timeAgo(value:string){const delta=Date.now()-new Date(value).getTime();if(delta<60000)return 'Just now';if(delta<3600000)return `${Math.floor(delta/60000)}m ago`;if(delta<86400000)return `${Math.floor(delta/3600000)}h ago`;return new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric'});}
export function Player({track,take,onStep}:{track:Track|null;take?:Take;onStep:(delta:number)=>void}){
 const audio=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false);const [position,setPosition]=useState(0);const [length,setLength]=useState(0);const [volume,setVolume]=useState(.8);const [loop,setLoop]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{setPlaying(false);setPosition(0);setLength(0);setError('');},[take?.audio_url]);
 useEffect(()=>{if(audio.current){audio.current.volume=volume;audio.current.loop=loop;}},[volume,loop,take?.audio_url]);
 const toggle=()=>{if(!audio.current||!take?.audio_url)return;if(audio.current.paused)audio.current.play().catch(()=>setError('This format cannot play here. Download it to listen.'));else audio.current.pause();};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(e.code==='Space'&&!['INPUT','TEXTAREA','SELECT','BUTTON','A'].includes(target.tagName)&&!document.querySelector('[role="dialog"]')){e.preventDefault();toggle();}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[take?.audio_url]);
 return <footer className="player"><div className="player-song"><div className="player-thumb">{track?.cover_url?<img src={track.cover_url} alt=""/>:<Music2 size={19}/>}</div><div><strong>{take?.audio_url?track?.title||'Untitled song':'Nothing playing yet'}</strong><span>{error|| (take?.audio_url?track?.artist||'Your recording':'Select a take or import a recording')}</span></div></div><div className="player-center"><div className="transport"><button className="icon-button" aria-label="Previous take" disabled={!take?.audio_url} onClick={()=>onStep(-1)}><SkipBack size={16}/></button><button className="play-button" aria-label={playing?'Pause':'Play'} disabled={!take?.audio_url} onClick={toggle}>{playing?<Pause size={17} fill="currentColor"/>:<Play size={17} fill="currentColor"/>}</button><button className="icon-button" aria-label="Next take" disabled={!take?.audio_url} onClick={()=>onStep(1)}><SkipForward size={16}/></button></div><div className="scrubber"><span>{duration(position)}</span><input aria-label="Playback position" type="range" min="0" max={length||1} step=".1" value={position} disabled={!take?.audio_url} onChange={e=>{const v=+e.target.value;if(audio.current)audio.current.currentTime=v;setPosition(v);}}/><span>{duration(length||take?.duration)}</span></div></div><div className="player-tools"><button className={`icon-button ${loop?'selected':''}`} aria-label="Repeat track" aria-pressed={loop} onClick={()=>setLoop(!loop)}><Repeat2 size={17}/></button><Volume2 size={17}/><input type="range" aria-label="Volume" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(+e.target.value)}/>{take?.audio_url?<a className="icon-button" href={take.audio_url} download aria-label="Download audio"><ArrowDownToLine size={17}/></a>:<span className="player-format">STEREO</span>}</div><audio ref={audio} src={take?.audio_url||undefined} preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={()=>setPosition(audio.current?.currentTime||0)} onLoadedMetadata={()=>setLength(audio.current?.duration||0)} onError={()=>{if(take?.audio_url)setError('Unable to play this file. Try downloading it.');}}/></footer>;
}
export function Empty({title,children}:{title:string;children:ReactNode}){return <div className="empty-state"><div className="empty-icon"><Disc3 size={30} strokeWidth={1}/></div><h3>{title}</h3><p>{children}</p></div>;}
