import {useState} from 'react';
import {ArrowUpRight,Check,Copy,ExternalLink,Loader2,Monitor,Server,ShieldCheck} from 'lucide-react';
import {Modal} from './components';
import type {Engine,Settings} from './types';

export default function SettingsDialog({settings,engine,onSave,onClose}:{settings:Settings;engine:Engine;onSave:(settings:Settings)=>Promise<void>;onClose:()=>void}){
 const [value,setValue]=useState(settings);const [busy,setBusy]=useState(false);const [remoteSaved,setRemoteSaved]=useState(settings.mode==='remote');const [error,setError]=useState('');const [copied,setCopied]=useState(false);
 const update=(data:Partial<Settings>)=>{setValue(v=>({...v,...data}));setRemoteSaved(false);};
 async function save(){setBusy(true);setError('');try{await onSave({...value,offline:true});setRemoteSaved(value.mode==='remote');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title="Music engine" subtitle="Choose where your songs are generated." onClose={onClose} wide><div className="settings-body"><div className="connection-choice"><button className={value.mode==='local'?'active':''} onClick={()=>update({mode:'local'})}><Monitor size={21}/><strong>This Mac</strong><span>Local Python runtime</span></button><button className={value.mode==='remote'?'active':''} onClick={()=>update({mode:'remote'})}><Server size={21}/><strong>GPU machine</strong><span>Connect through an SSH tunnel</span></button></div>
 <div className={`engine-report ${engine.ready?'ready':''}`}><span className="engine-dot"/><div><strong>{engine.ready?'Engine ready':'Setup required'}</strong><p>{engine.message||'Connect an installed YuE2 runtime to generate music.'}</p></div></div>
 {value.mode==='local'?<><div className="form-grid"><label className="full">Python executable<input value={value.python_path} onChange={e=>update({python_path:e.target.value})} placeholder="/path/to/YuE/.venv/bin/python" spellCheck={false}/></label><label>Device<select value={value.device} onChange={e=>update({device:e.target.value})}><option value="auto">Choose automatically</option><option value="mps">Apple GPU · experimental</option><option value="cuda">NVIDIA GPU</option></select></label><label>Memory budget (GiB)<input type="number" min="4" max="192" step="1" value={value.memory_budget_gib} onChange={e=>update({memory_budget_gib:+e.target.value})}/></label><label className="full">Music model<input value={value.model} onChange={e=>update({model:e.target.value})} spellCheck={false}/></label><label className="full">Audio decoder<input value={value.vae} onChange={e=>update({vae:e.target.value})} spellCheck={false}/></label></div><div className="check-row"><ShieldCheck size={15}/><span><strong>Uses models already on disk</strong><small>Download the music model and decoder separately, then select their folders or cached model IDs above.</small></span></div><details className="setup-details"><summary>How to install the music runtime</summary><p>In the YuE repository, create a separate Python environment. The interface itself does not require the music dependencies.</p><div className="command-block"><code>python3.12 -m venv .venv<br/>.venv/bin/python -m pip install .</code><button className="icon-button" aria-label="Copy installation commands" onClick={()=>{navigator.clipboard.writeText('python3.12 -m venv .venv\n.venv/bin/python -m pip install .').then(()=>setCopied(true)).catch(()=>setError('Select and copy the commands manually.'));}}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><p>Then enter that environment’s full Python path above. YuE2 documents Linux, NVIDIA BF16, and 24 GB VRAM. Apple GPU generation needs testing on your hardware.</p><a href="https://github.com/BureauObscura/YuE/blob/main/docs/generation.md" target="_blank" rel="noreferrer">Read the runtime guide <ArrowUpRight size={13}/></a></details></>:<><div className="form-grid"><label className="full">Forwarded Studio address<input type="url" value={value.remote_url} onChange={e=>update({remote_url:e.target.value})} placeholder="http://127.0.0.1:8767" spellCheck={false}/></label></div><div className="setup-details always"><p>Run Studio on the GPU machine with --forwarded-port 8767, then forward its port securely to your Mac:</p><div className="command-block"><code>ssh -N -L 8767:127.0.0.1:8766 user@gpu-host</code></div><p>Use the forwarded address above. The remote machine needs its own installed YuE runtime and model files. Its library is stored on that machine.</p>{remoteSaved&&<a className="secondary-button remote-open" href={value.remote_url} target="_blank" rel="noreferrer">Open remote Studio <ExternalLink size={14}/></a>}</div></>}
 <p className="privacy-note"><ShieldCheck size={14}/> Projects stay on this computer unless you send them to a connected service.</p>{error&&<p className="form-error" role="alert">{error}</p>}</div><div className="modal-footer"><a href="https://github.com/BureauObscura/YuE#license" target="_blank" rel="noreferrer" className="subtle-link">YuE2 · noncommercial license <ExternalLink size={12}/></a><button className="primary-button" onClick={save} disabled={busy}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>}Save & check connection</button></div></Modal>;
}
